apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: dev
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'spring-app'
        scrape_interval: 5s
        static_configs:
          - targets: [ '192.168.0.53:8081' ]
        metrics_path: /actuator/prometheus