services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - 8086:8080
      - 50000:50000
    volumes:
      - ./jenkins-home:/var/jenkins_home
    environment:
      - JENKINS_OPTS=--httpPort=8086