apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "kafka-ui-cluster"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "kafka-internal:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-external
  namespace: dev
spec:
  type: NodePort
  ports:
    - name: external
      port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: kafka-ui